### ISSUE TITLE
Compilation

### ISSUE THREAD

**Issue by bhagemeier** [onedata/oneclient#1]
Hi guys,

I'm having a hard time compiling oneclient. On a CentOS 7 I need to explicitly install packages in addition to the ones you nicely document in the README:

- mock for building an RPM
- CMake3, which is not in the default official repositories
- ninja-build is even difficult to find
- "Intel TBB NOT found!"
- glog not installed (actually needs glog-devel package)
- golang-devel
- libsodium-devel
- ...

I gave up here. Though I found out only very late that I was by default on the development branch, not the master. The master is a bit different, but also has its issues. I did not try and start over the entire process.

Now, my issue may seem like a rant, but this is not intended. You may want to include documentation about the missing packages or state on which system the configuration is supposed to work. A CentOS 7.2 does not quite cut it here.

Considering that the documentation mentions CMake 2.8, but CMake 3 is required by the CMakeLists.txt (cmake_minimum_required(VERSION 3.0.0)), the documentation may deserve some review anyhow.

Best regards,
Björn

**Comment by michalrw** [comment]
Hi,

Can you tell me exactly what you want to do? If you want to test oneclient, it would be easier to install it from packages (see https://onedata.org/download <https://onedata.org/download>). We are releasing versions 3.0 of onedata. It results in large revolution at github (we are using bitbucket during the development). You might not be able to compile the code from github for week or two because new instruction is needed (new builds are done by dockers).

Best regards,
Michał Wrzeszcz
Onedata Team

**Comment by bhagemeier** [comment]
Hi Michał,

thanks a lot for the clarification. I somehow directly went to compiling
from the sources, as they were the first thing I found when I searched
for oneclient a while back. I'll use the packages then.

Maybe you could add a pointer to the packages in the README, as I see
this problem very frequently in Open Source projects: installation from
the sources being described first and package installation only after
that or not at all.


Thanks again and
best regards,
Björn

Am 01.04.2016 um 20:08 schrieb Michał Wrzeszcz:
> Hi,
> 
> Can you tell me exactly what you want to do? If you want to test
> oneclient, it would be easier to install it from packages (see
> https://onedata.org/download <https://onedata.org/download>). We are
> releasing versions 3.0 of onedata. It results in large revolution at
> github (we are using bitbucket during the development). You might not be
> able to compile the code from github for week or two because new
> instruction is needed (new builds are done by dockers).
> 
> Best regards,
> Michał Wrzeszcz
> Onedata Team
> 
>> Wiadomość napisana przez Björn Hagemeier <notifications@github.com> w
> dniu 01.04.2016, o godz. 17:30:
>>
>> Hi guys,
>>
>> I'm having a hard time compiling oneclient. On a CentOS 7 I need to
> explicitly install packages in addition to the ones you nicely document
> in the README:
>>
>> mock for building an RPM
>> CMake3, which is not in the default official repositories
>> ninja-build is even difficult to find
>> "Intel TBB NOT found!"
>> glog not installed (actually needs glog-devel package)
>> golang-devel
>> libsodium-devel
>> ...
>> I gave up here. Though I found out only very late that I was by
> default on the development branch, not the master. The master is a bit
> different, but also has its issues. I did not try and start over the
> entire process.
>>
>> Now, my issue may seem like a rant, but this is not intended. You may
> want to include documentation about the missing packages or state on
> which system the configuration is supposed to work. A CentOS 7.2 does
> not quite cut it here.
>>
>> Considering that the documentation mentions CMake 2.8, but CMake 3 is
> required by the CMakeLists.txt (cmake_minimum_required(VERSION 3.0.0)),
> the documentation may deserve some review anyhow.
>>
>> Best regards,
>> Björn
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
> <https://github.com/onedata/oneclient/issues/1>
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/onedata/oneclient/issues/1#issuecomment-204498353>
> 


-- 
Dipl.-Inform. Björn Hagemeier
Federated Systems and Data
Juelich Supercomputing Centre
Institute for Advanced Simulation

Phone: +49 2461 61 1584
Fax  : +49 2461 61 6656
Email: b.hagemeier@fz-juelich.de
Skype: bhagemeier
WWW  : http://www.fz-juelich.de/jsc

JSC is the coordinator of the
John von Neumann Institute for Computing
and member of the
Gauss Centre for Supercomputing

-------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------
Forschungszentrum Juelich GmbH
52425 Juelich
Sitz der Gesellschaft: Juelich
Eingetragen im Handelsregister des Amtsgerichts Dueren Nr. HR B 3498
Vorsitzender des Aufsichtsrats: MinDir Dr. Karl Eugen Huthmacher
Geschaeftsfuehrung: Prof. Dr.-Ing. Wolfgang Marquardt (Vorsitzender),
Karsten Beneke (stellv. Vorsitzender), Prof. Dr.-Ing. Harald Bolt,
Prof. Dr. Sebastian M. Schmidt
-------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------

**Comment by michalrw** [comment]
Thank you for the advice. We will add a pointer when we will be updating README. If you have any questions, do not hesitate to write via e-mail or using our support chat room (see https://onedata.org/support <https://onedata.org/support>).

Best regards,
Michał Wrzeszcz
